# Before invoking this macro, make sure you first
# initialize the visualization system, eg.  /control/execute ../vis.mac

/vis/viewer/set/sectionPlane on 2 0 0 cm 1 0 0
/vis/viewer/set/style wireframe
/vis/verbose warnings
/vis/drawVolume worlds
/vis/viewer/set/targetPoint 0 0 380 cm
/vis/viewer/set/viewpointThetaPhi 90 180
/vis/viewer/zoomTo 15
/vis/viewer/set/autoRefresh true

# use /vis/ogl/export z380.eps to save the image to an eps file
